### ISSUE TITLE
bug和一些建议

### ISSUE THREAD

**Issue by 821938089** [letterk/legado-webui#1]
bug

<details>
<summary>Traceback </summary>

```
127.0.0.1 - - [29/May/2022 21:49:05] "GET /bookshelf/ HTTP/1.1" 500 -
127.0.0.1 - - [29/May/2022 21:49:05] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [29/May/2022 21:49:08] "GET / HTTP/1.1" 302 -
请求app获取书架
[2022-05-29 21:49:08,969] ERROR in app: Exception on /bookshelf/ [GET]
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 2051, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1501, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1499, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\flask\app.py", line 1485, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\github\legado-webui\app.py", line 277, in bookshelf
    return redirect(url_for("set_ip"))
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\flask\helpers.py", line 334, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\flask\helpers.py", line 321, in url_for
    rv = url_adapter.build(
  File "c:\users\user\appdata\local\programs\python\python38\lib\site-packages\werkzeug\routing.py", line 2301, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'set_ip'. Did you mean 'static' instead?
127.0.0.1 - - [29/May/2022 21:49:08] "GET /bookshelf/ HTTP/1.1" 500 -
```

</details>

似乎是因为 `set_ip` 入口端点函数被注释了导致了，我取消注释就好了

<hr>

建议，可以优化一下未读章节数的显示

<details>
<summary>修改后效果</summary>

![image](https://user-images.githubusercontent.com/8674809/170872771-07c94c87-965b-4183-8206-47e009939654.png)
</details>

<details>
<summary>代码</summary>

```html
<td>
  {% if book.unread %}
  <div id="unread">{{ book.unread }}</div>
  {% else %}
  <div id="unread" style="background-color: #bbb">
    {{ book.unread }}
  </div>
  {% endif %}
</td>
```
</details>

<hr>

建议加个源站点URL的显示，可以点击直接跳转到源站点

我给这个网站写了个站点规则，在阅读模式下翻页可以自动记书签，注意要关闭预载下一章，否则会多记到下一章
访问 [这个地址](http://localhost:5000) 就可以启用站点规则

**Comment by letterk** [comment]
这....好尴尬的感觉
自己写的一塌糊涂的被别人看见了

**Comment by letterk** [comment]
>我给这个网站写了个站点规则，在阅读模式下翻页可以自动记书签，注意要关闭预载下一章，否则会多记到下一章
访问 [这个地址](http://localhost:5000/) 就可以启用站点规则

我是故意写个按钮的, 阅读把保存进度api拆分出来我还高兴了一会儿, 非常讨厌自动书签. 我遇到忘记的线索会去翻前面的章节, 这样容易搞乱阅读进度

**Comment by 821938089** [comment]
啊这，那好吧，你用 `127.0.0.1:5000` 访问是不会启用站点规则的。
别尬，我推一下我写的阅读书源解析库，能写出这种东西，自己觉得挺牛逼的，虽然也是写的也是一塌糊涂，能跑就行，用的人一般不会看怎么实现的。
